### ISSUE TITLE
Design and prototype monster AI

### ISSUE THREAD

**Issue by NathanLovato** [GDQuest/godot-open-rpg#19]
The monsters should be able to target their opponents based on flexible criterias:

- They could try to target the character that's weakest to them
- They could heal once when their life goes below a certain threshold

Etc. I am not sure how to best do this so every option available on the monsters not hardcoded in the base class, without creating a complex gambit system or something like that. Feedback and ideas welcome!

**Comment by salvob41** [comment]
I would gladly take this take of prototyping monster AI. But maybe it would be better, having a getter for the stats' element? 
What do you think about adding chance in taking one or another action (as it is rawly impleemented in PR #24 ) ?

**Comment by salvob41** [comment]
for the healing action, we need to decide how to implement those. See #25

**Comment by NathanLovato** [comment]
v0.2 is already getting a lot of new features, moving this to a future milestone

**Comment by GresilleSiffle** [comment]
It would be useful to have a little visual document like a _decision tree_, or a _behavior tree_ that acts as a reference for the current AI implementation.

Something that even a newcomer can read and figure out how the AI algorithm work.

We can find [examples of them here](https://www.gamedev.net/articles/programming/artificial-intelligence/the-total-beginners-guide-to-game-ai-r4942/).

What do you think about that?

**Comment by NathanLovato** [comment]
And with a flexible system like this, we could build AI for allies as well, have an AI-controlled party member

**Comment by nhydock** [comment]
If you want a nice visual way to do AI composition, I recommend looking at something like Final Fantasy XII's Gambit system.  Not saying we need to have an in-game AI customization feature, but the general structure and templating that gambits provides is a great starting point and pretty flexible.  It's easy to represent enemy AI just as easily with it as character AI.

**Comment by NathanLovato** [comment]
I was thinking about FF XII's gambits with the example above 😄
But I'd still go with a tree structure so we can have multiple conditions, and the benefit of a flexible system for people who'd like to code an RPG with more complex gameplay: e.g. having APs and the ability to use multiple actions per turn.

**Comment by Dharengo** [comment]
I like the idea of a tree as well, but it _may_ lead to a bit of a noob trap where people use complex tree structures to solve a simple problem. What I'm thinking of right now is a gambit-style queue. At the root would be the AI node which doesn't require any input from the developer. The AI node would iterate down its list of children. Lets call these children "Behaviors" for now.

Each Behavior would have a number of "Condition" nodes as children. The behavior node would call the `evaluate()` method on each Condition node. Possible types of Condition nodes could be:
-Percentage chance
-Own HP greater than/equal to/smaller than x
-Amount of turns since start of battle
-Amount of turns since the last time this action was used
-An ally has HP lower than x
-An enemy has x status (like being stunned or poisoned)

If `evaluate()` returns `false` on any of the Condition nodes, the AI node would iterate to the next Behavior node. If all Condition nodes return `true`, the action associated with that Behavior would be carried out.

The Behavior Node itself would have a field for the developer to put in an Action.

As for deciding on the target. I'm still torn between whether to make it its own type of Node which you would add as a child to a Behavior Node, or whether to just make it a dropdown list on the Inspector on the Behavior Node. I'm leaning towards making it a Node but I keep swaying back and forth on this. Perhaps some input on this would make it easier to decide.

Either way, possible types of targets could be:
-Random enemy
-Specific ally
-Lowest HP enemy
-Lowest HP ally
-The enemy/ally that meets the condition in one of the Condition nodes (such as "Ally HP lower than x" or "An enemy has x status")
