### ISSUE TITLE
Preview the mana cost on the bar when a round button is in focus

### ISSUE THREAD

**Issue by NathanLovato** [GDQuest/godot-open-rpg#83]

**Comment by nsmith339** [comment]
Is this to be displayed as a tooltip, font overlay, or some specific way?

**Comment by NathanLovato** [comment]
I envisioned it more like having the portion of the bar that is going to get eaten blink

**Comment by rudehero** [comment]
I've made an initial (simplified) attempt on a fork located at:
https://github.com/rudehero/godot-open-rpg/tree/mana_preview

The mana bar is overlayed with a different color (non-blinking) to indicate the mana cost.

Happy to receive any feedback or thoughts on improvement.  Otherwise, I'd be happy to submit a PR if you'd like.

**Comment by NathanLovato** [comment]
@rudehero Thanks, if you want me to review your code, could you please open a PR?

**Comment by rudehero** [comment]
Submitted:
https://github.com/GDquest/godot-open-rpg/pull/187
